### ISSUE TITLE
Image Author URL and Colour not being pulled in

### ISSUE THREAD

**Issue by ljclark** [ethercreative/splash#4]
Can'y get this to pull in the Image author URL and the color of the image. 

I've set the following fields to capture the above, but not working (the image author is fine). They fields are applied to the asset volumes field layout too. 

Image Author URL `imageAuthorUrl` -> Plain Text (tried URL too)

Image Colour `imageColour` -> Colour 

Any ideas why it's not pulling in that info?

Thanks 
Lewis

**Comment by Tam** [comment]
Just tested the latest version and it's working fine, I'd recommend upgrading and trying again.
